### ISSUE TITLE
Fix className mismatch between server and client

### ISSUE THREAD

**Issue by vripoche** [smooth-code/smooth.js#11]
When we use the Emotion `css` prop in component, the following warning appears in console (dev mode):

```react-dom.development.js:506 Warning: Prop `className` did not match. Server: "Headline__Container-amo8ay-1 sc-lhVmIH gLqGDj" Client: "Headline__Container-amo8ay-1 sc-iAyFgw cYlwyx"```

Example in code base:

```
<Container css={css`background-color: red;`}>
...
</Container>
```

Despite this, the CSS are well applied.

**Comment by neoziro** [comment]
Yeah I know, I have this issue in a lot of projects but the error only occurs in development. I think it is not a big deal, but yeah it is still problematic.

**Comment by neoziro** [comment]
Should be fixed now.
